[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "frontmatter-utils"
version = "0.27.0"
description = "A Python library and CLI tool for parsing and searching front matter in files"
readme = "README.md"
requires-python = ">=3.7"
authors = [
	{ name = "Gerald Nguyen The Huy" }
]
license = { text = "MIT" }
dependencies = [
	"PyYAML>=6.0"
]
classifiers = [
	"Development Status :: 3 - Alpha",
	"Intended Audience :: Developers",
	"License :: OSI Approved :: MIT License",
	"Operating System :: OS Independent",
	"Programming Language :: Python :: 3",
	"Programming Language :: Python :: 3.7",
	"Programming Language :: Python :: 3.8",
	"Programming Language :: Python :: 3.9",
	"Programming Language :: Python :: 3.10",
	"Programming Language :: Python :: 3.11",
]

[project.urls]
Homepage = "https://github.com/geraldnguyen/frontmatter-utils"

[project.scripts]
fmu = "fmu.cli:main"
